- job:
    name: ceph-deploy
    node: trusty
    project-type: matrix
    defaults: global
    disabled: false
    display-name: 'ceph-deploy'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    parameters:
      - string:
          name: BRANCH
          description: "The git branch or tag to build"

      - bool:
          name: RELEASE
          description: "If checked, it will use the key for releases, otherwise it will use the autosign one."

    scm:
      - git:
          url: https://github.com/ceph/ceph-deploy.git
          branches:
            - $BRANCH
          browser: githubweb
          browser-url: http://github.com/ceph/ceph-deploy.git
          skip-tag: true
          timeout: 20

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - squeeze
            - wheezy
            - precise
            - trusty
            - jessie
            - centos6.5
            - centos7
            - rhel6.5
            - rhel7

    builders:
      - shell: !include-raw ../../build/setup
      - shell: !include-raw ../../build/build

    publishers:
      - archive:
          artifacts: '*-repo/**, dist/**'
          allow-empty: true
          latest-only: false
