- job:
    name: radosgw-agent
    node: trusty
    project-type: matrix
    defaults: global
    disabled: false
    display-name: 'radosgw-agent'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    parameters:
      - string:
          name: BRANCH
          description: "The git branch or tag to build"

      - bool:
          name: RELEASE
          description: "If checked, it will use the key for releases, otherwise it will use the autosign one."

    scm:
      - git:
          skip-tag: true
          url: https://github.com/ceph/radosgw-agent.git
          branches:
            - $BRANCH
          browser: auto
          timeout: 20

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - wheezy
            - precise
            - trusty
            - jessie
            - centos6
            - centos7

    builders:
      - shell:
          !include-raw ../../build/build

    publishers:
      - archive:
          artifacts: '*-repo/**, dist/**'
          allow-empty: true
          latest-only: false
