- job:
    name: mariner-installer-pull-requests
    description: Build and package mariner-installer for each GitHub PR
    project-type: matrix
    axes:
      - axis:
          name: Arch
          type: label-expression
          values:
            - x86_64
      - axis:
          name: Dist
          type: label-expression
          values:
            - trusty
    block-downstream: false
    block-upstream: false

    properties:
      - github:
          url: https://github.com/ceph/mariner-installer/

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    scm:
      - git:
          url: https://github.com/ceph/mariner-installer
          basedir: mariner-installer
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: githubweb
          browser-url: https://github.com/ceph/mariner-installer
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - dmick
            - ktdreyer
            - trhoden
          org-list:
            - ceph
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    builders:
      - shell:
          # Note that we're including the main "mariner-installer" job's build steps here.
          !include-raw ../../../mariner-installer/build/build

    publishers:
      - github-notifier
