- job:
    name: ceph-build-arm64
    project-type: matrix
    disabled: true
    defaults: global
    display-name: 'ceph-build-arm64'
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    parameters:
      - string:
          name: BRANCH
          description: Branch used by ceph-setup-arm64
    execution-strategy:
      combination-filter: (DIST == "xenial" && ARCH == "arm64")
    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - arm64
      - axis:
          type: label-expression
          name: DIST
          values:
            - xenial

    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      - copyartifact:
          project: ceph-setup-arm64
          filter: 'dist/**'
          which-build: build-param
          param: 'BRANCH'
      # general setup
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup
      # debian build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup_pbuilder
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build_rpm

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
