- job:
    name: ceph-ansible-rpm
    node: 'centos7 && x86_64 && small'
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'ceph-ansible: RPMs'
    description: 'Build RPMs for every ceph-ansible Git branch'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    discard-old-builds: true
    logrotate:
      daysToKeep: 1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../scripts/build_utils.sh
            - ../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
