- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser-url: https://github.com/ceph/ceph-build
          branches:
                  - evelu-build
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-build"

- scm:
    name: ceph
    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
                - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true
          basedir: "ceph"

- job:
    name: ceph-pull-requests
    project-type: freestyle
    defaults: global
    concurrent: true
    node: huge && (centos7 || trusty) && rebootable
    display-name: 'ceph: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph/
    logrotate:
      daysToKeep: 15
      numToKeep: 300
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: ''
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false

    scm:
      - ceph-build
      - ceph

    builders:
      - shell: "cd ceph; ../ceph-build/ceph-pull-requests/build/build build"

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: "cd ceph; ../ceph-build/ceph-pull-requests/build/build failure"
