- job:
    name: ceph-installer-pull-requests
    description: Unit-test the ceph-installer for each GitHub PR
    project-type: freestyle
    node: trusty && small
    block-downstream: false
    block-upstream: false
    defaults: global
    display-name: 'ceph-installer: Pull Requests'
    quiet-period: 5
    retry-count: 3

    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: 15
      artifactNumToKeep: 15

    properties:
      - github:
          url: https://github.com/ceph/ceph-installer/

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          admin-list:
            - alfredodeza
            - dmick
            - ktdreyer
            - andrewschoen
          org-list:
            - ceph
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/ceph-installer
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - github-notifier
