# kabi-tracking kmod RPMs for libceph, CephFS, and RDB for RHEL 7.

# Uses the MultiSCM plugin to combine these two repos:
- scm:
    name: ceph-kmod-rpm
    scm:
      - git:
          url: https://github.com/ceph/ceph-kmod-rpm.git
          branches:
            - origin/master
          browser: githubweb
          browser-url: https://github.com/ceph/ceph-kmod-rpm/
          skip-tag: true
          wipe-workspace: false

- scm:
    name: ceph-client
    scm:
      - git:
          url: https://github.com/ceph/ceph-client.git
          branches:
            - $BRANCH
          browser: githubweb
          browser-url: https://github.com/ceph/ceph-client/
          skip-tag: true
          wipe-workspace: false
          basedir: ceph-client

# ... the combined repo:
- scm:
    name: ceph-kmod-rpm-and-ceph-client
    scm:
      - ceph-kmod-rpm
      - ceph-client

# ...now the actual Jenkins job definition:
- job:
    name: ceph-kmod-rpm
    project-type: matrix
    defaults: global
    disabled: false
    display-name: 'ceph-kmod-rpm'
    concurrent: true
    quiet-period: 5
    retry-count: 3
    logrotate:
      daysToKeep: -1
      numToKeep: 20
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    scm:
      - ceph-kmod-rpm-and-ceph-client

    parameters:
      - string:
          name: BRANCH
          description: "The git branch or tag to build in ceph-client"

    axes:
      - axis:
          type: label-expression
          name: label
          values:
            - rhel7

    triggers:
      - pollscm: "@hourly"

    builders:
      - shell: "make clean || :"
      - shell: "./configure"
      - shell: "make"

    publishers:
      - archive:
          artifacts: 'results_ceph-kmod/**/*.rpm'
          allow-empty: false
          latest-only: false
