- job:
    name: ceph-dev-build
    project-type: matrix
    defaults: global
    display-name: 'ceph-dev-build'
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    execution-strategy:
       combination-filter: DIST==AVAILABLE_DIST && (ARCH=="x86_64" || (ARCH == "arm64" && (DIST == "xenial" || DIST == "centos7")))
    axes:
      - axis:
          type: label-expression
          name: MACHINE_SIZE
          values:
            - huge
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
            - arm64
      - axis:
          type: label-expression
          name: AVAILABLE_DIST
          values:
            - trusty
            - xenial
            - centos7
            - jessie
      - axis:
          type: dynamic
          name: DIST
          values:
            - DISTROS



    builders:
      - shell: |
          echo "Cleaning up top-level workarea (shared among workspaces)"
          rm -rf dist
          rm -rf venv
          rm -rf release
      - copyartifact:
          project: ceph-dev-setup
          filter: 'dist/**'
          which-build: last-successful
      - inject:
          properties-file: ${WORKSPACE}/dist/sha1
      # general setup
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup
      # debian build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup_pbuilder
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build_rpm

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
