- job:
    axes:
    - axis:
        name: arch
        type: label-expression
        values:
        - x86_64
    - axis:
        name: dist
        type: label-expression
        values:
        - centos
        - rhel
        - rhel7
        - precise
        - trusty
        - wheezy
    - axis:
        name: label
        type: slave
        values:
        - calamari-buildslave
    block-downstream: false
    block-upstream: false
    builders:
    - shell: !include-raw ../../build/build
    combination-filter: dist != 'wheezy'  && dist != 'rhel'
    description: ''
    execution-strategy:
      run-sequentially: false
    logrotate:
      artifactDaysToKeep: '-1'
      artifactNumToKeep: '-1'
      daysToKeep: '-1'
      numToKeep: '-1'
    name: 'calamari-server'
    node: calamari-buildslave
    parameters:
    - string:
        default: master
        description: ''
        name: BRANCH
    project-type: matrix
    properties:
    - github:
        url: https://github.com/ceph/calamari/
    publishers:
    - archive:
        allow-empty: false
        artifacts: $BRANCH/*
        default-excludes: true
        fingerprint: false
        only-if-success: false
    - description-setter:
        description: \1
        regexp: 'BRANCH: (\S+)'
        regexp-for-failed: ''
        set-for-matrix: false
    scm:
    - git:
        basedir: Diamond
        branches:
          - '*/calamari'
        url: git@github.com:ceph/Diamond
