---
- include: repo.yml

- include: dependencies_yum.yml

- name: Install Jenkins
  yum: name=jenkins state=latest
  register: jenkins_install

- include: config.yml

- include: cli.yml

- include: plugins.yml

- include: config.yml
