- job:
    name: rtslib-fb-trigger
    node: master
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/rtslib-fb
    discard-old-builds: true
    logrotate:
      daysToKeep: 1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/rtslib-fb.git
          branches:
            - 'origin/master*'
            - 'origin/testing*'
            - 'origin/wip*'
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - trigger-builds:
        - project: 'rtslib-fb'
          predefined-parameters: |
            BRANCH=${GIT_BRANCH}
            FORCE=True
