- job:
    name: ceph-deploy-docs
    node: trusty
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'ceph-deploy: docs build'
    concurrent: false
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-deploy
    logrotate:
      daysToKeep: -1
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    triggers:
      - pollscm: "* * * * *"

    scm:
      - git:
          url: https://github.com/ceph/ceph-deploy.git
          branches:
            - master
          browser: githubweb
          browser-url: https://github.com/ceph/ceph-deploy.git
          skip-tag: true
          timeout: 20

    builders:
      - shell:
          !include-raw ../../build/build
