- job:
    name: ceph-qa-suite-pull-requests
    node: gitbuilder-cdep-deb-trusty-amd64-basic
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'ceph-qa-suite: Pull Requests'
    concurrent: false
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-qa-suite/
    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cron: '* * * * *'
          admin-list:
            - alfredodeza
            - ktdreyer
            - trhoden
          org-list:
            - ceph
          white-list:
            - jcsp
            - gregsfortytwo
            - dmick
            - GregMeno
            - dzafman
            - dillaman
            - dachary
            - liewegas
          trigger-phrase: ''
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/ceph-qa-suite.git
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: githubweb
          browser-url: https://github.com/ceph/ceph-qa-suite
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - shell:
          !include-raw ../../build/build

    publishers:
      - github-notifier
