# Safe-restart Jenkins
- name: restart jenkins
  command: java -jar {{ jenkins.cli_dest }} -s http://localhost:{{ jenkins_port }} safe-restart
  when: okay_with_restart == "y"

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: stop nginx
  service:
    name: nginx
    state: stopped
