- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  when: okay_with_restart == "y"

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: stop nginx
  service:
    name: nginx
    state: stopped
