- project:
    name: ceph-volume-ansible-prs-lvm
    distro:
      - xenial
      - centos7
    objectstore:
      - bluestore
      - filestore
    scenario:
      - create
      - prepare_activate
    subcommand:
      - lvm

    jobs:
      - 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'

- project:
    name: ceph-volume-ansible-prs-simple
    distro:
      - xenial
      - centos7
    objectstore:
      - bluestore
      - filestore
    scenario:
      - activate
    subcommand:
      - simple

    jobs:
      - 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'


- job-template:
    name: 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'
    display-name: 'ceph-volume {subcommand}: Pull Request [{distro}-{objectstore}-{scenario}]'
    node: vagrant&&libvirt
    concurrent: true
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true
    logrotate:
      daysToKeep: 30

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          only-trigger-phrase: true
          trigger-phrase: 'jenkins test ceph-volume {subcommand} {distro}-{objectstore}-{scenario}'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "ceph-volume {subcommand} testing {distro}-{objectstore}-{scenario}"
          started-status: "ceph-volume {subcommand} running {distro}-{objectstore}-{scenario}"
          success-status: "ceph-volume {subcommand} {distro}-{objectstore}-{scenario} OK"
          failure-status: "ceph-volume {subcommand} {distro}-{objectstore}-{scenario} failed"

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            DISTRO={distro}
            OBJECTSTORE={objectstore}
            SUBCOMMAND={subcommand}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
