- job:
    name: jenkins-job-builder
    node: trusty
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'Jenkins Job Builder'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3

    triggers:
      - pollscm: "H */3 * * *"
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          branches:
            - master
          browser: githubweb
          browser-url: http://github.com/ceph/ceph-build.git
          timeout: 20

    builders:
      - shell: "bash jenkins-job-builder/build/build"
