- job:
    name: jenkins-job-builder
    node: trusty
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'Jenkins Job Builder'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-build

    triggers:
      - github

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true

    scm:
      - git:
          url: https://github.com/ceph/ceph-build
          branches:
            - master
          browser: auto
          timeout: 20

    builders:
      - shell: "bash jenkins-job-builder/build/build"

    publishers:
      - postbuildscript:
          builders:
            - shell: 'rm $HOME/.jenkins_jobs.ini'
        script-only-if-succeeded: false
        script-only-if-failed: false
