- project:
    name: ceph-container-prs
    os:
      - centos7
      - xenial
    ceph-version:
      - jewel
      - luminous
    test:
      - cluster
      - filestore_osds_container
      - bluestore_osds_container
      - docker_cluster_collocation
    exclude:
       - ceph-version: jewel
         test: bluestore_osds_container
    jobs:
        - 'ceph-container-prs-ceph_ansible-{ceph-version}-{os}-{test}'


- job-template:
    name: 'ceph-container-prs-ceph_ansible-{ceph-version}-{os}-{test}'
    node: vagrant&&libvirt&&centos7
    concurrent: true
    defaults: global
    display-name: 'ceph-container: Pull Requests [ceph_ansible-{ceph-version}-{os}-{test}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-container
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test ceph_ansible-{ceph-version}-{os}-{test}'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: ceph_ansible-{ceph-version}-{os}-{test}"
          started-status: "Running: ceph_ansible-{ceph-version}-{os}-{test}"
          success-status: "OK - ceph_ansible-{ceph-version}-{os}-{test}"
          failure-status: "FAIL - ceph_ansible-{ceph-version}-{os}-{test}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO=ceph_ansible-{ceph-version}-{os}-{test}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
