- job:
    name: nfs-ganesha-trigger
    node: master
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/nfs-ganesha/nfs-ganesha
    discard-old-builds: true
    logrotate:
      daysToKeep: 1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/nfs-ganesha/nfs-ganesha
          browser: auto
          # The default is to build and publish every branch.
          # Uncomment this for testing:
          branches:
            - 'origin/next'
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/notify
      - trigger-builds:
        - project: 'nfs-ganesha'
          predefined-parameters: |
            CEPH_BRANCH=master

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
