---

# These values allow the nginx role to fully configure load balancing and
# regular hosts.
nginx_hosts:
  - fqdn: "grafana.ceph.com"
    app_name: "grafana"
    proxy_pass: "http://127.0.0.1:3000"
  - fqdn: "shaman.ceph.com"
    app_name: "shaman"
    upstreams:
      name: "shaman"
      strategy: "least_conn"
      servers:
        - "1.shaman.ceph.com"
        - "2.shaman.ceph.com"
