- job:
    name: lab-cop
    node: small && xenial
    defaults: global
    display-name: 'lab-cop'
    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    builders:
      - shell:
          !include-raw:
            - ../../build/build

