- scm:
    name: lab-cop
    scm:
      - git:
          url: https://github.com/ceph/teuthology.git
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "lab-cop"

- job:
    name: lab-cop
    node: small && xenial
    defaults: global
    display-name: 'lab-cop'
    properties:
      - github:
          url: https://github.com/ceph/teuthology/
    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    scm:
      - lab-cop

    builders:
      - shell:
          !include-raw:
            - ../../build/build

