- job:
    name: ceph-volume-pr
    display-name: 'ceph-volume: Pull Request tox tests'
    node: x86_64
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true
    logrotate:
      daysToKeep: 14

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          only-trigger-phrase: true
          trigger-phrase: 'jenkins test ceph-volume tox'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "ceph-volume tox testing"
          started-status: "ceph-volume tox running"
          success-status: "ceph-volume tox OK"
          failure-status: "ceph-volume tox failed"

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
