- job:
    name: bz-mill
    defaults: global
    display-name: 'bz-mill'

    triggers:
      - timed: '@hourly'

    builders:
      - shell:
          !include-raw:
            - ../../build/head
            - ../../build/map_namespace_to_query
            - ../../build/build
