- job:
    name: bz-mill
    defaults: global
    display-name: 'bz-mill'
- project:
    name: bz-mill

    triggers:
      - timed: '@hourly'

    builders:
      - shell:
          !include-raw:
            - ../../build/build
