- job:
    name: bz-mill
    defaults: global
    display-name: 'bz-mill'
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: 15

    triggers:
      - timed: '@hourly'

    builders:
      - shell:
          !include-raw:
            - ../../build/head
            - ../../build/map_namespace_to_query
            - ../../build/build
