- job:
    block-downstream: false
    block-upstream: false
    builders:
    - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
    description: ''
    logrotate:
      artifactDaysToKeep: '-1'
      artifactNumToKeep: '-1'
      daysToKeep: '-1'
      numToKeep: '-1'
    name: 'calamari-server-trusty'
    node: small && trusty
    parameters:
    - string:
        default: ''
        description: ''
        name: BRANCH
    project-type: freestyle
    properties:
    - github:
        url: https://github.com/ceph/calamari/
    publishers:
    - archive:
        allow-empty: false
        artifacts: $BRANCH/*.deb,$BRANCH/calamari-repo-trusty.tar.gz
        default-excludes: true
        fingerprint: false
        only-if-success: false
    - fingerprint:
        files: $BRANCH/*.deb,$BRANCH/calamari-repo-trusty.tar.gz
    scm:
      - git:
          url: https://github.com/ceph/calamari.git
          branches:
            - $BRANCH
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
