- job:
    name: ceph-ansible-docs-pull-requests
    node: small && (centos7 || trusty)
    project-type: freestyle
    defaults: global
    display-name: 'ceph-ansible: docs pull requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: -1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test docs'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Docs"
          started-status: "checking if docs build"
          success-status: "docs built successfully "
          failure-status: "docs could not build correctly"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible
          browser: auto
          skip-tag: true
          timeout: 20

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
