- project:
    name: ceph-docker-nightly
    os:
      - centos7
      - xenial
    ceph-version:
      - jewel
      - luminous
    test:
      - cluster
      - dedicated_journal
      - dmcrypt_journal_collocation
    jobs:
        - 'ceph-docker-nightly-ceph_ansible-{ceph-version}-{os}-{test}'

- job-template:
    name: 'ceph-docker-nightly-ceph_ansible-{ceph-version}-{os}-{test}'
    node: vagrant&&libvirt
    concurrent: true
    defaults: global
    display-name: 'ceph-docker: Nightly tests [ceph_ansible-{ceph-version}-{os}-{test}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-docker
    logrotate:
      daysToKeep: -1
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: BRANCH
          description: "A ceph-docker branch to test"
          default: master

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-docker.git
          branches:
            - ${{BRANCH}}
          browser: auto
          timeout: 20

    builders:
      - inject:
          properties-content: |
            SCENARIO=ceph_ansible-{ceph-version}-{os}-{test}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
