- project:
    name: ceph-ansible-prs
    release_before_luminous:
      - jewel
    release_after_luminous:
      - luminous
    scenario_before_luminous:
      - ansible2.2-centos7_cluster
      - ansible2.2-xenial_cluster
      - ansible2.2-journal_collocation
      - ansible2.2-dmcrypt_journal
      - ansible2.2-dmcrypt_journal_collocation
      - ansible2.2-docker_cluster
      - ansible2.2-docker_dedicated_journal
      - ansible2.2-docker_dmcrypt_journal_collocation
      - ansible2.2-purge_cluster
      - ansible2.2-purge_dmcrypt
      - ansible2.2-update_dmcrypt
      - ansible2.2-update_cluster
      - ansible2.2-purge_docker_cluster
      - ansible2.2-update_docker_cluster
    scenario_after_luminous:
      - ansible2.2-centos7_cluster
      - ansible2.2-xenial_cluster
      - ansible2.2-journal_collocation
      - ansible2.2-dmcrypt_journal
      - ansible2.2-dmcrypt_journal_collocation
      - ansible2.2-docker_cluster
      - ansible2.2-docker_dedicated_journal
      - ansible2.2-docker_dmcrypt_journal_collocation
      - ansible2.2-purge_cluster
      - ansible2.2-purge_dmcrypt
      - ansible2.2-update_dmcrypt
      - ansible2.2-update_cluster
      - ansible2.2-purge_docker_cluster
      - ansible2.2-update_docker_cluster
      - ansible2.2-bluestore_cluster
      - ansible2.2-bluestore_journal_collocation
      - ansible2.2-bluestore_dmcrypt_journal
      - ansible2.2-bluestore_dmcrypt_journal_collocation
      - ansible2.2-bluestore_docker_cluster
      - ansible2.2-bluestore_docker_dedicated_journal
      - ansible2.2-bluestore_docker_dmcrypt_journal_collocation
    jobs:
        - 'ceph-ansible-prs-{release_before_luminous}-{scenario_before_luminous}'
        - 'ceph-ansible-prs-{release_after_luminous}-{scenario_after_luminous}'

- job-template:
    name: 'ceph-ansible-prs-{release_before_luminous}-{scenario_before_luminous}'
    node: vagrant&&libvirt
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release_before_luminous}-{scenario_before_luminous}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test {release_before_luminous}-{scenario_before_luminous}'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release_before_luminous}-{scenario_before_luminous}"
          started-status: "Running: {release_before_luminous}-{scenario_before_luminous}"
          success-status: "OK - {release_before_luminous}-{scenario_before_luminous}"
          failure-status: "FAIL - {release_before_luminous}-{scenario_before_luminous}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario_before_luminous}
            RELEASE={release_before_luminous}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
      - naginator:
          rerun-unstable-builds: true
          fixed-delay: 60
          max-failed-builds: 3

- job-template:
    name: 'ceph-ansible-prs-{release_after_luminous}-{scenario_after_luminous}'
    node: vagrant&&libvirt
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release_after_luminous}-{scenario_after_luminous}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test {release_after_luminous}-{scenario_after_luminous}'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release_after_luminous}-{scenario_after_luminous}"
          started-status: "Running: {release_after_luminous}-{scenario_after_luminous}"
          success-status: "OK - {release_after_luminous}-{scenario_after_luminous}"
          failure-status: "FAIL - {release_after_luminous}-{scenario_after_luminous}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario_after_luminous}
            RELEASE={release_after_luminous}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
      - naginator:
          rerun-unstable-builds: true
          fixed-delay: 60
          max-failed-builds: 3
