# tests that will auto start for every PR created and run on smithi
- project:
    name: ceph-ansible-prs-auto
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    ansible_version:
      - ansible2.4
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - docker_cluster_collocation
    jobs:
        - 'ceph-ansible-prs-auto'

- project:
    name: ceph-ansible-prs-oldstable-trigger
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - jewel
    ansible_version:
      - ansible2.4
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
    jobs:
        - 'ceph-ansible-prs-oldstable-trigger'

# tests that will not auto start when a PR is created, but
# they can be requested with a trigger phrase. Run on smithi.
- project:
    name: ceph-ansible-prs-trigger-smithi
    slave_labels: 'vagrant && libvirt && smithi'
    release:
      - luminous
    ansible_version:
      - ansible2.4
    scenario:
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_non_container
      - purge_filestore_osds_container
      - purge_bluestore_osds_non_container
      - purge_bluestore_osds_container
      - update_cluster
      - update_docker_cluster
      - switch_to_containers
    jobs:
        - 'ceph-ansible-prs-trigger'

# tests that will not auto start when a PR is created, but
# they can be requested with a trigger phrase. Run on OVH.
- project:
    name: ceph-ansible-prs-trigger-ovh
    slave_labels: 'vagrant && libvirt && !smithi && centos7'
    release:
      - luminous
    ansible_version:
      - ansible2.4
    scenario:
      - bluestore_osds_non_container
      - bluestore_osds_container
      - filestore_osds_non_container
      - filestore_osds_container
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - lvm_osds
      - purge_lvm_osds
      - bluestore_lvm_osds
    jobs:
        - 'ceph-ansible-prs-trigger'

# tests that use packages from shaman.ceph.com and
# do not auto start when a PR is created, but can be
# requested with a trigger phrase
- project:
    name: ceph-ansible-prs-dev
    slave_labels: 'vagrant && libvirt && !smithi && centos7'
    release:
      - dev
    ansible_version:
      - ansible2.4
    scenario:
      - lvm_osds
      - purge_lvm_osds
      - bluestore_lvm_osds
    jobs:
      - 'ceph-ansible-prs-trigger'

- job-template:
    name: 'ceph-ansible-prs-{release}-{ansible_version}-{scenario}'
    id: 'ceph-ansible-prs-oldstable-trigger'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{ansible_version}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*'
          trigger-phrase: '^jenkins test oldstable {release}-{ansible_version}-{scenario}|jenkins test oldstable.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{ansible_version}-{scenario}"
          started-status: "Running: {release}-{ansible_version}-{scenario}"
          success-status: "OK - {release}-{ansible_version}-{scenario}"
          failure-status: "FAIL - {release}-{ansible_version}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            ANSIBLE_VERSION={ansible_version}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown

- job-template:
    name: 'ceph-ansible-prs-{release}-{ansible_version}-{scenario}'
    id: 'ceph-ansible-prs-auto'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{ansible_version}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*'
          trigger-phrase: '^jenkins test {release}-{ansible_version}-{scenario}|jenkins test all.*'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{ansible_version}-{scenario}"
          started-status: "Running: {release}-{ansible_version}-{scenario}"
          success-status: "OK - {release}-{ansible_version}-{scenario}"
          failure-status: "FAIL - {release}-{ansible_version}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            ANSIBLE_VERSION={ansible_version}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown

- job-template:
    name: 'ceph-ansible-prs-{release}-{ansible_version}-{scenario}'
    id: 'ceph-ansible-prs-trigger'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{ansible_version}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*'
          trigger-phrase: '^jenkins test {release}-{ansible_version}-{scenario}|jenkins test all.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{ansible_version}-{scenario}"
          started-status: "Running: {release}-{ansible_version}-{scenario}"
          success-status: "OK - {release}-{ansible_version}-{scenario}"
          failure-status: "FAIL - {release}-{ansible_version}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            ANSIBLE_VERSION={ansible_version}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
