- project:
    name: ceph-ansible-prs
    release:
      - luminous
    ansible_version:
      - ansible2.3
    scenario:
      - centos7_cluster
      - xenial_cluster
      - journal_collocation
      - dmcrypt_journal
      - dmcrypt_journal_collocation
      - docker_cluster
      - docker_dedicated_journal
      - docker_dmcrypt_journal_collocation
      - purge_cluster
      - purge_dmcrypt
      - update_dmcrypt
      - update_cluster
      - purge_docker_cluster
      - update_docker_cluster
      - bluestore_cluster
      - bluestore_journal_collocation
      - bluestore_dmcrypt_journal
      - bluestore_dmcrypt_journal_collocation
      - bluestore_docker_cluster
      - bluestore_docker_dedicated_journal
      - bluestore_docker_dmcrypt_journal_collocation
    jobs:
        - 'ceph-ansible-prs-{release}-{ansible_version}-{scenario}'

- job-template:
    name: 'ceph-ansible-prs-{release}-{ansible_version}-{scenario}'
    node: vagrant&&libvirt
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{release}-{ansible_version}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: 'jenkins test {release}-{ansible_version}-{scenario}'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {release}-{ansible_version}-{scenario}"
          started-status: "Running: {release}-{ansible_version}-{scenario}"
          success-status: "OK - {release}-{ansible_version}-{scenario}"
          failure-status: "FAIL - {release}-{ansible_version}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            ANSIBLE_VERSION={ansible_version}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
