- job:
    name: ceph-docs
    node: docs
    project-type: freestyle
    defaults: global
    concurrent: false
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true
    logrotate:
      daysToKeep: 1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph
          browser: auto
          # The default is to build and publish every branch.
          # Uncomment this for testing:
          #branches:
          #  - 'origin/master'
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      - shell:
          !include-raw ../../build/build
