- project:
    name: ceph-ansible-nightly-jewel
    release:
      - jewel
    ansible_version:
      - ansible2.2
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - update_docker_cluster
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
    ceph_ansible_branch:
      - stable-2.2
    jobs:
      - 'ceph-ansible-nightly-{release}-{ansible_version}-{ceph_ansible_branch}-{scenario}'

    name: ceph-ansible-nightly-jewel
    release:
      - jewel
    ansible_version:
      - ansible2.4
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - update_docker_cluster
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
    ceph_ansible_branch:
      - stable-2.2
      - stable-3.0
    jobs:
      - 'ceph-ansible-nightly-{release}-{ansible_version}-{ceph_ansible_branch}-{scenario}'

- project:
    name: ceph-ansible-nightly-luminous
    release:
      - luminous
    ansible_version:
      - ansible2.4
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - lvm_osds
      - purge_lvm_osds
      - docker_cluster_collocation
      - update_docker_cluster
      - switch_to_containers
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - bluestore_osds_non_container
      - bluestore_osds_container
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
      - purge_bluestore_osds_container
      - purge_bluestore_osds_non_container
    ceph_ansible_branch:
      - stable-3.0
      - master
    jobs:
        - 'ceph-ansible-nightly-{release}-{ansible_version}-{ceph_ansible_branch}-{scenario}'

- job-template:
    name: 'ceph-ansible-nightly-{release}-{ansible_version}-{ceph_ansible_branch}-{scenario}'
    node: vagrant&&libvirt&&centos7
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Nightly [{release}-{ansible_version}-{ceph_ansible_branch}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: CEPH_ANSIBLE_BRANCH
          description: "The ceph-ansible branch (or tag) to test"
          default: "{ceph_ansible_branch}"

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - $CEPH_ANSIBLE_BRANCH
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            ANSIBLE_VERSION={ansible_version}
            CEPH_ANSIBLE_BRANCH={ceph_ansible_branch}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell: !include-raw ../../build/teardown
