- job:
    name: jenkins-slave-chef-pull-requests
    node: trusty
    project-type: freestyle
    defaults: global
    disabled: false
    display-name: 'Jenkins Slave Chef Recipies: Pull Requests'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/jenkins-slave-chef

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cron: '* * * * *'
          admin-list:
            - alfredodeza
            - ktdreyer
          org-list:
            - ceph
          trigger-phrase: 'retest this please'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: false
          auto-close-on-fail: false

    scm:
      - git:
          url: https://github.com/ceph/jenkins-slave-chef.git
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: githubweb
          browser-url: https://github.com/ceph/jenkins-slave-chef/
          skip-tag: true
          timeout: 20

    builders:
      - shell: "rake"
