---

- hosts: all
  sudo: true
  user: ubuntu
  vars:
   - jenkins_user: 'jenkins-build'
  tasks:
    - name: create a jenkins-build user
      user: name=jenkins-build comment="Jenkins Build Slave User"

    - name: Create .ssh directory
      file: path=/home/jenkins-build/.ssh
            state=directory

    - name: set the authorized keys
      authorized_key: user=jenkins-build key="{{ lookup('file', 'files/ssh/keys/jenkins_build.pub') }}"

    - name: ensure the build dir exists
      sudo: yes
      lineinfile:
        dest: /etc/sudoers
        regexp: '^jenkins-build ALL'
        line: 'jenkins-build   ALL=(ALL:ALL) NOPASSWD:ALL'
        backrefs: yes
        validate: 'visudo -cf %s'

    - name: ensure the build dir exists
      file: path=/home/{{ jenkins_user }}/build state=directory owner={{ jenkins_user }}

    - name: Install RPM requirements
      sudo: yes
      yum: name={{ item }} state=present
      with_items:
        - createrepo
        - epel-release
        - java-1.7.0-openjdk
        - git
        #- rpm-sign
      when: ansible_pkg_mgr  == "yum"

    # Run the equivalent of "apt-get update" as a separate step
    - apt: update_cache=yes
      when: ansible_pkg_mgr  == "apt"

    - name: Install DEB requirements
      sudo: yes
      apt: name={{ item }} state=present
      with_items:
        - git
        - fakeroot
        - fakeroot-ng
        - debhelper
        - reprepro
        - dchroot
        - devscripts
        - pbuilder
        - pkg-config
        - openjdk-7-jre
        - python-dev
        - python-pip
        - python-virtualenv
        # ceph-docs job:
        - doxygen
        - ditaa
        - ant
        # teuthology-docs job:
        - libmysqlclient-dev
        - libevent-dev
        - libffi-dev
      when: ansible_pkg_mgr  == "apt"

    - name: install python-jenkins
      sudo: true
      pip: name=python-jenkins

    - name: add docs.ceph.com host key
      sudo: true
      known_hosts: path='/etc/ssh/ssh_known_hosts'
      name='docs.ceph.com'
      # docs.ceph.com.pub is the output of `ssh-keyscan docs.ceph.com`
      key="{{ lookup('file', 'ssh/hostkeys/docs.ceph.com.pub') }}"

    - name: register the new slave to jenkins master
      jenkins-node:
        username: "{{ api_user }}"
        uri: "{{ api_uri }}"
        password: "{{ token }}"
        # relies on a convention to set a unique name that allows a reverse
        # mapping from Jenkins back to whatever service created the current
        # node
        name: "{{ nodename }}+{{ ansible_default_ipv4.address }}"
        labels: "{{ labels }}"
        host: "{{ ansible_default_ipv4.address }}"
        credentialsId: '39fa150b-b2a1-416e-b334-29a9a2c0b32d'
        remoteFS: '/home/jenkins-build/build'
