---
- include: repo.yml

- include: dependencies.yml

- include: nginx.yml

- include: letsencrypt.yml
  tags:
    - letsencrypt

- include: ufw.yml
  tags:
    - ufw

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  register: jenkins_install

- include: config.yml

- include: plugins.yml
  when: okay_with_restart == "y"
  tags:
    - plugins

# This should only get run the first time the role is run.
# The variables should be passed as --extra-vars via ansible-playbook command
- include: auth.yml
  when: github_oauth_client is defined and github_oauth_secret is defined
  tags:
    - auth

- include: config.yml
