---
- include: repo.yml
  when: ansible_pkg_mgr  == "yum"

- include: dependencies_yum.yml
  when: ansible_pkg_mgr  == "yum"

- include: nginx.yml

- name: Install Jenkins
  yum: name=jenkins state=present
  register: jenkins_install

- include: config.yml

- include: plugins.yml

- include: config.yml
