---
- include: repo.yml

- include: dependencies.yml

- include: nginx.yml

- name: Install Jenkins with Yum
  yum: name=jenkins state=present
  register: jenkins_install
  when: ansible_pkg_mgr  == "yum"

- name: Install Jenkins with Apt
  apt: name=jenkins state=present
  register: jenkins_install
  when: ansible_pkg_mgr  == "apt"

- include: config.yml

- include: plugins.yml

- include: config.yml
