---
- include: repo.yml

- include: dependencies.yml

- include: nginx.yml

- include: letsencrypt.yml
  tags:
    - letsencrypt

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  register: jenkins_install

- include: config.yml

- include: plugins.yml

- include: config.yml
