---
- name: Add Jenkins GPG Key
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present

- name: Add the jenkins repo
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
    state: present
    update_cache: true
