---
- name: Install python-devel
  yum: name=python-devel state=present

- name: Install python-pycurl
  yum: name=python-pycurl state=present

- name: Add Jenkins GPG Key
  rpm_key: state=present key=https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Create the repo file for Jenkins
  copy: src=jenkins.repo
        dest=/etc/yum.repos.d/
        owner=root
        group=root
        mode=0644
