---

- hosts: all
  user: vagrant
  roles:
    - nginx
    - grafana
  vars_files:
    - vars/load-balance-vars.yml
  vars:
     fqdn: "grafana.ceph.com"
     app_name: "grafana"
     development_server: true
     ansible_ssh_port: 22
     # These are defined in `vars/load-balance-vars.yml` but defaulting to what
     # is used in production. For local development, update these to match the
     # hosts used in your local development environment
     #nginx_hosts:
     #  - fqdn: "grafana.ceph.com"
     #    app_name: "grafana"
     #    proxy_pass: "http://127.0.0.1:3000"
     #  - fqdn: "shaman.ceph.com"
     #    app_name: "shaman"
     #    upstreams:
     #      - name: "shaman"
     #        strategy: "least_conn"
     #        servers:
     #          - "1.shaman.ceph.com"
     #          - "2.shaman.ceph.com"

     # only needed when enabling Github Auth
     # github_client_id: "111aaa222"
     # github_client_secret: "qwerty1234"
