---

- hosts: jenkins_master
  user: cm
  become: true
  roles:
    - ansible-jenkins
  vars:
    - nginx_processor_count: 20
    - nginx_connections: 2048
    - ansible_ssh_port: 2222
    - plugins:
      - 'github'
      - 'translation'
      - 'preSCMbuildstep'
      - 'copyartifact'
      - 'ssh-slaves'
      - 'scm-api'
      - 'multiple-scms'
      - 'rebuild'
      - 'publish-over-ssh'
      - 'nested-view'
      - 'jenkins-multijob-plugin'
      - 'dynamic-axis'
      - 'ghprb'
      - 'github'
      - 'github-api'
      - 'git'
      - 'git-client'
      - 'envinject'
      - 'credentials'
      - 'copyartifact'
      - 'github-oauth'
      - 'mask-passwords'
      - 'description-setter'
      - 'postbuildscript'
      - 'jobConfigHistory'

    - jenkins_port: 8080
    - prefix: '/build'
    - xmx: 8192
    # Email support
    #- email:
    #  smtp_host: 'mail.example.com'
    #  smtp_ssl: 'true'
    #  default_email_suffix: '@example.com'
