- job:
    name: mariner-installer
    description: Build and package mariner-installer
    project-type: matrix
    axes:
    - axis:
        name: Arch
        type: label-expression
        values:
        - x86_64
    - axis:
        name: Dist
        type: label-expression
        values:
        - trusty
    block-downstream: false
    block-upstream: false

    properties:
    - github:
        url: https://github.com/ceph/mariner-installer/

    scm:
    - git:
        skip-tag: true
        basedir: mariner-installer
        url: https://github.com/ceph/mariner-installer
        branches:
         - $BRANCH

    execution-strategy:
      run-sequentially: false

    builders:
    - shell:
        !include-raw ../../build/build
    concurrent: false
    parameters:
    - string:
        default: master
        description: 'The git branch or tag to build'
        name: BRANCH

    publishers:
    - archive:
        allow-empty: false
        artifacts: $BRANCH/*
        default-excludes: true
        fingerprint: false
        only-if-success: false
    - description-setter:
        regexp: '^BRANCH: (\S+)'
        set-for-matrix: false
