- job:
    block-downstream: false
    block-upstream: false
    builders:
    - shell: !include-raw ../../build/build
    description: ''
    logrotate:
      artifactDaysToKeep: '-1'
      artifactNumToKeep: '-1'
      daysToKeep: '-1'
      numToKeep: '10'
    name: 'calamari-server-rhel7'
    node: vagrant
    parameters:
    - string:
        default: ''
        description: ''
        name: BRANCH
    project-type: freestyle
    properties:
    - github:
        url: https://github.com/ceph/calamari/
    publishers:
    - archive:
        allow-empty: false
        artifacts: $BRANCH/*.rpm,$BRANCH/calamari-repo-rhel7.tar.gz
        default-excludes: true
        fingerprint: false
        only-if-success: false
    - fingerprint:
        files: $BRANCH/*.rpm,$BRANCH/calamari-repo-rhel7.tar.gz
    scm:
    - git:
        basedir: Diamond
        branches:
          - '*/calamari'
        url: git@github.com:ceph/Diamond
