- job:
    name: ceph-build
    project-type: matrix
    defaults: global
    disabled: false
    display-name: 'ceph-build'
    concurrent: false
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph

    execution-strategy:
      combination-filter: Arch=="x86_64"

    axes:
      - axis:
          type: label-expression
          name: Arch
          values:
            - x86_64
      - axis:
          type: label-expression
          name: Distro
          values:
            - wheezy-pbuild
            - precise-pbuild
            - trusty-pbuild
            - centos6.5
            - centos7
            - rhel6.5
            - rhel7

    builders:
      - shell: |
          echo "Cleaning up workarea"
          rm -rf dist
          rm -rf release
      - copyartifact:
          project: ceph-setup
          filter: 'dist/**'
          which-build: last-successful
      - shell:
          !include-raw ../../build/setup
      - shell:
          !include-raw ../../build/setup_pbuilder
      - shell:
          !include-raw ../../build/build_deb
      - shell:
          !include-raw ../../build/build_rpm

    publishers:
      - archive:
          artifacts: 'dist/**'
          allow-empty: false
          latest-only: false
