- job:
    name: ceph-build
    project-type: matrix
    defaults: global
    disabled: false
    display-name: 'ceph-build'
    concurrent: false
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph

    execution-strategy:
      combination-filter: |
        (Arch=="x86_64") || (Arch=="i386" && (Distro=="wheezy-pbuild" || Distro=="precise-pbuild"))

    axes:
      - axis:
          type: label-expression
          name: Arch
          values:
            - x86_64
            - i386
      - axis:
          type: label-expression
          name: Distro
          values:
            - wheezy-pbuild
            - precise-pbuild
            - trusty-pbuild
            - centos6.3
            - centos6.4
            - centos6.5
            - centos7
            - rhel6.3
            - rhel6.4
            - rhel6.5
            - rhel7
            - fedora20

    builders:
      - shell: |
          echo "Cleaning up workarea"
          rm -rf dist
          rm -rf release
      - copyartifact:
          project: ceph-setup
          filter: 'dist/**'
          which-build: last-successful
      - shell:
          !include-raw ../../build/build1
      - shell:
          !include-raw ../../build/build2

    publishers:
      - archive:
          artifacts: 'dist/**'
          allow-empty: false
          latest-only: false
