- job:
    name: ceph-build
    project-type: matrix
    defaults: global
    display-name: 'ceph-build'
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - jessie
            #- wheezy
            #- precise
            - trusty
            #- centos6
            - centos7

    builders:
      - shell: |
          echo "Cleaning up workarea"
          rm -rf dist
          rm -rf release
      - copyartifact:
          project: ceph-setup
          filter: 'dist/**'
          which-build: last-successful
      # general setup
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup
      # debian build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/setup_pbuilder
            - ../../build/build_deb
      # rpm build scripts
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build_rpm

    publishers:
      - archive:
          artifacts: 'dist/**'
          allow-empty: false
          latest-only: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
