- job:
    name: ceph-package
    defaults: global
    disabled: false
    display-name: 'ceph-package'
    node: package
    concurrent: false
    block-downstream: false
    block-upstream: false
    logrotate:
      daysToKeep: -1
      numToKeep: 20
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    axes:
      - axis:
          type: label-expression
          name: ARCH
          values:
            - x86_64
      - axis:
          type: label-expression
          name: DIST
          values:
            - squeeze
            - wheezy
            - precise
            - trusty
            - jessie
            - centos6.5
            - centos7
            - rhel6.5
            - rhel7

    builders:

      # "Clean up any prior stuff"
      - shell: 'rm -rf Arch=* 2>/dev/null; true'

      - copyartifact:
          project: ceph-build
          filter: 'dist/**'
          which-build: last-successful

      - shell:
          !include-raw ../../build/build
