- scm:
    name: ceph-ansible
    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-ansible"

- scm:
    name: ceph-build
    scm:
      - git:
          url: https://github.com/ceph/ceph-build.git
          browser-url: https://github.com/ceph/ceph-build
          timeout: 20
          skip-tag: true
          wipe-workspace: false
          basedir: "ceph-build"

- job:
    name: ceph-ansible-pull-requests
    project-type: freestyle
    defaults: global
    display-name: 'ceph-ansible: Pull Requests'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
    logrotate:
      daysToKeep: 15
      numToKeep: 30
      artifactDaysToKeep: -1
      artifactNumToKeep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          trigger-phrase: ''
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing Playbooks"
          started-status: "Running ansible playbook"
          success-status: "Run completed"
          failure-status: "Playbook run failed with errors"

    scm:
      - ceph-ansible
      - ceph-build

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build
