- job:
    block-downstream: false
    block-upstream: false
    builders:
    - copyartifact:
        filter: $BRANCH/calamari-clients-build-output.tar.gz
        flatten: true
        project: calamari-clients-precise-vagrant
        target: ${WORKSPACE}
        which-build: last-successful
    - shell: !include-raw ../../build/build
    concurrent: false
    description: ''
    logrotate:
      artifactDaysToKeep: '-1'
      artifactNumToKeep: '-1'
      daysToKeep: '-1'
      numToKeep: '-1'
    name: 'calamari-clients-wheezy'
    node: vagrant
    parameters:
    - string:
        default: ''
        description: ''
        name: BRANCH
    project-type: freestyle
    publishers:
    - archive:
        allow-empty: false
        artifacts: $BRANCH/calamari-clients*deb
        default-excludes: true
        fingerprint: false
        only-if-success: false
    - fingerprint:
        files: $BRANCH/calamari-clients*deb
        record-artifacts: false
    scm:
    - git:
        basedir: calamari-clients
        branches: '*/${BRANCH}'
        url: git@github.com:ceph/calamari-clients.git
